defaultPortal: PROD

# Optionally set the default mode for all accounts
defaultMode: publish

# Override default HTTP timeout in milliseconds
httpTimeout: 30000

# Disable usage tracking
allowUsageTracking: false

# List of accounts that are intended to be used
portals:
  # Account set up to use Personal Access Key authentication
  - name: PROD
    portalId: 456
    authType: personalaccesskey
    auth:
      personalAccessKey: 1234567890
      tokenInfo:
        expiresAt: '2019-05-02T02:52:05.233Z'
        refreshToken: 84d22710-4cb7-5581-ba05-35f9945e5e8e
        accessToken: >-
          CJDVnLanLRICEQIYyLu8LyDh9E4opf1GMhkAxGuU5XN_O2O2QhX0khw7cwIkPkBRHye-OfIADgLBAAADAIADAAAAAAAAAAJCGQC8a5TlhtSU8T-2mVLxOBpxS18aM42oGKk

