const HUBSPOT_PROJECT_COMPONENTS_GITHUB_PATH =
  'HubSpot/hubspot-project-components';
const HUBSPOT_PROJECT_COMPONENTS_VERSION = 'v0.1.0';
const DEFAULT_PROJECT_TEMPLATE_BRANCH = 'main';

module.exports = {
  HUBSPOT_PROJECT_COMPONENTS_GITHUB_PATH,
  HUBSPOT_PROJECT_COMPONENTS_VERSION,
  DEFAULT_PROJECT_TEMPLATE_BRANCH,
};
