#!/usr/bin/env node
const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');
const { setArgsOverrides, getTestConfig } = require('./lib/env');
const { CONFIG_FILE_NAME } = require('./lib/constants');
const path = require('path');
const Jasmine = require('jasmine');
const rimraf = require('rimraf');
const cmd = require('./tests/helpers/cmd');
const Reporter = require('jasmine-terminal-reporter');
const reporter = new Reporter({
  isVerbose: true,
  includeStackTrace: true,
});

setArgsOverrides(
  yargs(hideBin(process.argv))
    .option('portalId', {
      alias: ['p', 'accountId'],
      type: 'string',
      description: 'Account Id',
    })
    .option('cliPath', {
      alias: 'c',
      type: 'string',
      description: 'CLI Path',
    })
    .option('personalAccessKey', {
      alias: 'pak',
      type: 'string',
      description: 'Personal Access Key',
    })
    .option('clientId', {
      type: 'string',
      default: false,
      description: 'ClientId for oauth',
    })
    .option('clientSecret', {
      type: 'string',
      default: false,
      description: 'Client secret for oauth',
    })
    .option('refreshToken', {
      type: 'string',
      default: false,
      description: 'Refresh token for oauth',
    })
    .option('qa', {
      type: 'boolean',
      default: false,
      description: 'Set this if you are using a app.hubspotqa.com site',
    })
    .option('headless', {
      type: 'boolean',
      default: false,
      description: 'Run the tests in headless mode',
    })
    .option('debug', {
      type: 'boolean',
      default: false,
      description: 'Add additional debugging information',
    }).argv
);

(async () => {
  try {
    const testRunner = new Jasmine();
    testRunner.exitOnCompletion = false;
    testRunner.loadConfigFile(path.join(__dirname, 'jasmine.json'));
    testRunner.addReporter(reporter);

    global.config = getTestConfig();
    global.cli = cmd.createCli(global.config.cliPath);

    await global.cli.execute(
      ['init', `--c="${CONFIG_FILE_NAME}"`],
      [cmd.ENTER, global.config.personalAccessKey, cmd.ENTER, cmd.ENTER]
    );

    const result = await testRunner.execute();

    rimraf.sync(CONFIG_FILE_NAME);
    process.exit(result.overallStatus === 'passed' ? 0 : 1);
  } catch (e) {
    console.log(e)
  }
})();
