import yargs, { Argv, ArgumentsCamelCase } from 'yargs';
import fs from 'fs-extra';
import { cloneGithubRepo } from '@hubspot/local-dev-lib/github';
import { getCwd } from '@hubspot/local-dev-lib/path';
import { getProjectMetadata } from '@hubspot/project-parsing-lib/projects';
import {
  addAccountOptions,
  addConfigOptions,
  addUseEnvironmentOptions,
} from '../../../lib/commonOpts.js';
import {
  getProjectConfig,
  writeProjectConfig,
} from '../../../lib/projects/config.js';
import { handleProjectCreationFlow } from '../../../lib/projects/create/index.js';
import { generateComponentPaths } from '../../../lib/projects/create/v2.js';
import { updateHsMetaFilesWithAutoGeneratedFields } from '../../../lib/projects/components.js';
import { showMcpPromotionNudge } from '../../../lib/mcp/promotion.js';
import { getProjectCreateFailureReason } from '../../../lib/projects/create/tracking.js';
import { trackCommandUsage } from '../../../lib/usageTracking.js';
import { EXIT_CODES } from '../../../lib/enums/exitCodes.js';
import { PROJECT_WITH_APP } from '../../../lib/constants.js';
import { uiLogger } from '../../../lib/ui/logger.js';
import projectCreateCommand, { ProjectCreateJsonArgs } from '../create.js';

vi.mock('../../../lib/commonOpts');
vi.mock('@hubspot/local-dev-lib/config');
vi.mock('@hubspot/local-dev-lib/config/state');
vi.mock('@hubspot/local-dev-lib/github');
vi.mock('@hubspot/local-dev-lib/path');
vi.mock('@hubspot/project-parsing-lib/projects');
vi.mock('../../../lib/projects/config.js');
vi.mock('../../../lib/projects/create/index.js');
vi.mock('../../../lib/projects/create/v2.js');
vi.mock('../../../lib/projects/components.js');
vi.mock('../../../lib/errorHandlers/index.js');
vi.mock('../../../lib/projects/create/tracking.js');
vi.mock('../../../lib/mcp/promotion.js');
vi.mock('fs-extra', () => ({
  default: {
    readFileSync: vi.fn(),
    ensureDirSync: vi.fn(),
  },
}));
vi.mock('../../../lib/ui/SpinniesManager.js', () => ({
  default: {
    add: vi.fn(),
    fail: vi.fn(),
    succeed: vi.fn(),
  },
}));

const mockedFs = vi.mocked(fs);
const mockedCloneGithubRepo = vi.mocked(cloneGithubRepo);
const mockedGetCwd = vi.mocked(getCwd);
const mockedGetProjectMetadata = vi.mocked(getProjectMetadata);
const mockedGetProjectConfig = vi.mocked(getProjectConfig);
const mockedWriteProjectConfig = vi.mocked(writeProjectConfig);
const mockedHandleProjectCreationFlow = vi.mocked(handleProjectCreationFlow);
const mockedGenerateComponentPaths = vi.mocked(generateComponentPaths);
const mockedUpdateHsMetaFilesWithAutoGeneratedFields = vi.mocked(
  updateHsMetaFilesWithAutoGeneratedFields
);
const mockedShowMcpPromotionNudge = vi.mocked(showMcpPromotionNudge);
const mockedGetProjectCreateFailureReason = vi.mocked(
  getProjectCreateFailureReason
);
const mockedTrackCommandUsage = vi.mocked(trackCommandUsage);
const processExitSpy = vi.spyOn(process, 'exit');

describe('commands/project/create', () => {
  const yargsMock = yargs as Argv;

  beforeEach(() => {
    // @ts-expect-error Mock implementation
    processExitSpy.mockImplementation(() => {});
    mockedGetCwd.mockReturnValue('/cwd');
    mockedHandleProjectCreationFlow.mockResolvedValue({
      selectProjectTemplatePromptResponse: {
        projectTemplate: {
          name: 'app-template',
          label: 'App template',
          path: 'app-template',
        },
        componentTemplates: [],
      },
      projectNameAndDestPromptResponse: {
        name: 'test-project',
        dest: 'test-project',
      },
      projectContents: 'app',
    } as Awaited<ReturnType<typeof handleProjectCreationFlow>>);
    mockedGetProjectConfig.mockImplementation(() => {
      throw new Error('No project config found');
    });
    mockedGenerateComponentPaths.mockReturnValue(['src']);
    mockedCloneGithubRepo.mockResolvedValue(true);
    mockedFs.readFileSync.mockReturnValue(
      JSON.stringify({ name: 'starter', srcDir: 'src' })
    );
    mockedWriteProjectConfig.mockReturnValue(true);
    mockedGetProjectMetadata.mockResolvedValue({
      hsMetaFiles: [],
      components: {},
    } as Awaited<ReturnType<typeof getProjectMetadata>>);
    mockedUpdateHsMetaFilesWithAutoGeneratedFields.mockResolvedValue();
    mockedShowMcpPromotionNudge.mockResolvedValue(undefined);
    mockedGetProjectCreateFailureReason.mockReturnValue('unknown');
  });

  describe('command', () => {
    it('should have the correct command structure', () => {
      expect(projectCreateCommand.command).toEqual(['create', 'init']);
    });
  });

  describe('describe', () => {
    it('should provide a description', () => {
      expect(projectCreateCommand.describe).toBeDefined();
    });
  });

  describe('builder', () => {
    it('should support the correct options', () => {
      projectCreateCommand.builder(yargsMock);

      expect(addAccountOptions).toHaveBeenCalledTimes(1);
      expect(addAccountOptions).toHaveBeenCalledWith(yargsMock);

      expect(addConfigOptions).toHaveBeenCalledTimes(1);
      expect(addConfigOptions).toHaveBeenCalledWith(yargsMock);

      expect(addUseEnvironmentOptions).toHaveBeenCalledTimes(1);
      expect(addUseEnvironmentOptions).toHaveBeenCalledWith(yargsMock);
    });

    it('should define project creation options', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      const exampleSpy = vi.spyOn(yargsMock, 'example');
      const conflictsSpy = vi.spyOn(yargsMock, 'conflicts');

      projectCreateCommand.builder(yargsMock);

      expect(optionsSpy).toHaveBeenCalledWith(
        expect.objectContaining({
          name: expect.any(Object),
          dest: expect.any(Object),
          template: expect.any(Object),
          'template-source': expect.any(Object),
          'platform-version': expect.any(Object),
          'project-base': expect.any(Object),
          distribution: expect.any(Object),
          auth: expect.any(Object),
          features: expect.any(Object),
        })
      );

      expect(conflictsSpy).toHaveBeenCalledWith('template', 'features');
      expect(exampleSpy).toHaveBeenCalled();
    });

    it('should define platform version option with correct choices', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      projectCreateCommand.builder(yargsMock);

      const optionsCall = optionsSpy.mock.calls[0][0];
      expect(optionsCall['platform-version']).toEqual(
        expect.objectContaining({
          describe: 'The target platform version for the new project.',
          type: 'string',
          choices: [
            '2025.2',
            '2026.03-beta',
            '2026.03',
            '2026.09-beta',
            '2026.09',
            '2027.03-beta',
          ],
          default: '2026.09',
        })
      );
    });

    it('should define project base option with correct choices', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      projectCreateCommand.builder(yargsMock);

      const optionsCall = optionsSpy.mock.calls[0][0];
      expect(optionsCall['project-base']).toEqual(
        expect.objectContaining({
          describe: 'The top level component to include in the project.',
          type: 'string',
          choices: ['empty', 'app'],
        })
      );
    });

    it('should define distribution option with correct choices', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      projectCreateCommand.builder(yargsMock);

      const optionsCall = optionsSpy.mock.calls[0][0];
      expect(optionsCall.distribution).toEqual(
        expect.objectContaining({
          describe: 'How the app will be distributed.',
          type: 'string',
          choices: ['private', 'marketplace'],
        })
      );
    });

    it('should define auth option with correct choices', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      projectCreateCommand.builder(yargsMock);

      const optionsCall = optionsSpy.mock.calls[0][0];
      expect(optionsCall.auth).toEqual(
        expect.objectContaining({
          describe: 'Authentication model for the app.',
          type: 'string',
          choices: ['oauth', 'static'],
        })
      );
    });

    it('should define features option as array', () => {
      const optionsSpy = vi.spyOn(yargsMock, 'options');
      projectCreateCommand.builder(yargsMock);

      const optionsCall = optionsSpy.mock.calls[0][0];
      expect(optionsCall.features).toEqual(
        expect.objectContaining({
          describe:
            'Features to include in the project. Only valid if project-base is app',
          type: 'array',
        })
      );
    });
  });

  describe('handler', () => {
    const getArgs = () =>
      ({
        _: ['project', 'create'],
        d: false,
        debug: false,
        derivedAccountId: 123456,
        platformVersion: '2026.03',
      }) as ArgumentsCamelCase<ProjectCreateJsonArgs>;

    it('should show MCP promotion nudge after successful project creation', async () => {
      await projectCreateCommand.handler(getArgs());

      expect(mockedShowMcpPromotionNudge).toHaveBeenCalledWith(
        'project create'
      );
      expect(processExitSpy).toHaveBeenCalledWith(EXIT_CODES.SUCCESS);
    });

    it('should output project info as JSON and skip the nudge when formatOutputAsJson is true', async () => {
      await projectCreateCommand.handler({
        ...getArgs(),
        formatOutputAsJson: true,
      });

      expect(uiLogger.json).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'test-project',
          location: expect.stringContaining('test-project'),
          platformVersion: '2026.03',
          projectBase: PROJECT_WITH_APP,
        })
      );
      expect(mockedShowMcpPromotionNudge).not.toHaveBeenCalled();
      // The success box would pollute stdout and break JSON parsing, so it
      // must be suppressed in JSON mode.
      expect(
        mockedUpdateHsMetaFilesWithAutoGeneratedFields
      ).toHaveBeenCalledWith(
        expect.anything(),
        expect.anything(),
        expect.anything(),
        expect.objectContaining({ showSuccessMessage: false })
      );
    });

    it('should not show MCP promotion nudge when project creation fails', async () => {
      mockedHandleProjectCreationFlow.mockRejectedValue(
        new Error('Failed to create project')
      );

      await projectCreateCommand.handler(getArgs());

      expect(mockedShowMcpPromotionNudge).not.toHaveBeenCalled();
      expect(processExitSpy).toHaveBeenCalledWith(EXIT_CODES.ERROR);
    });

    it('tracks the download step with the classified failure reason when the download fails', async () => {
      mockedCloneGithubRepo.mockRejectedValue(new Error('Not found'));
      mockedGetProjectCreateFailureReason.mockReturnValue('github-not-found');

      await projectCreateCommand.handler(getArgs());

      expect(mockedGetProjectCreateFailureReason).toHaveBeenCalledWith(
        expect.any(Error)
      );
      expect(mockedTrackCommandUsage).toHaveBeenCalledWith(
        'project-create',
        expect.objectContaining({
          successful: false,
          step: 'download-project:github-not-found',
        }),
        123456
      );
      expect(processExitSpy).toHaveBeenCalledWith(EXIT_CODES.ERROR);
    });

    it('tracks the creation-flow step with the classified failure reason when the flow fails', async () => {
      mockedHandleProjectCreationFlow.mockRejectedValue(
        new Error('Rate limited')
      );
      mockedGetProjectCreateFailureReason.mockReturnValue('github-rate-limit');

      await projectCreateCommand.handler(getArgs());

      expect(mockedGetProjectCreateFailureReason).toHaveBeenCalledWith(
        expect.any(Error)
      );
      expect(mockedTrackCommandUsage).toHaveBeenCalledWith(
        'project-create',
        expect.objectContaining({
          successful: false,
          step: 'project-creation-flow:github-rate-limit',
        }),
        123456
      );
    });
  });
});
