on:
  push:
    tags:
      - '*'
  # Scheduled jobs will only run on the default branch
  schedule:
    - cron: '* */5 * * *' # Run every 5 hours
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Sleep when triggered by new tag to wait for npm publish
      - name: Sleep For 3 Mins
        run: sleep 180s
        shell: bash
      - name: Scheduled Test Slack Report
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Test Latest CLI Release
        run: |
          npx --yes --package=@hubspot/cli@latest --call='hs --help'
        shell: bash
