on:
  schedule:
    - cron: '30 16 * * 1-5' # Run Monday through Friday at 9:30am
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: actions/checkout@v4
        with:
          # Always checkout the main branch
          ref: main
          # Do a deep checkout
          fetch-depth: 0
          # Fetch all the release tags
          fetch-tags: true
      - name: Check for unreleased changes
        run: node .github/scripts/unreleasedChanges.js
      - name: Unreleased changes Slack Report
        uses: ravsamhq/notify-slack-action@v2
        if: ${{ env.LOG != '' }} # Only post if there is a log
        with:
          status: ${{ job.status }}
          notify_when: 'success'
          notification_title: 'Unreleased Changes in the CLI'
          message_format: '${{ env.LOG }}'
          footer: '<{run_url}|View Run> | <https://github.com/HubSpot/hubspot-cli/compare/v${{env.LATEST_TAG}}...main|View latest Diff in GitHub> | <https://github.com/HubSpot/hubspot-cli/compare/v${{env.NEXT_TAG}}...main|View next Diff in GitHub>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
